<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Juanjo Doblas">

<title>Análisis exploratorio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="analisis_exploratorio_files/libs/clipboard/clipboard.min.js"></script>
<script src="analisis_exploratorio_files/libs/quarto-html/quarto.js"></script>
<script src="analisis_exploratorio_files/libs/quarto-html/popper.min.js"></script>
<script src="analisis_exploratorio_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="analisis_exploratorio_files/libs/quarto-html/anchor.min.js"></script>
<link href="analisis_exploratorio_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="analisis_exploratorio_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="analisis_exploratorio_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="analisis_exploratorio_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="analisis_exploratorio_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción">1 - Introducción</a>
  <ul class="collapse">
  <li><a href="#descripción-de-las-variables" id="toc-descripción-de-las-variables" class="nav-link" data-scroll-target="#descripción-de-las-variables">1.1 - Descripción de las variables</a></li>
  </ul></li>
  <li><a href="#tratamiento-de-datos-composicionales" id="toc-tratamiento-de-datos-composicionales" class="nav-link" data-scroll-target="#tratamiento-de-datos-composicionales">2 - Tratamiento de datos composicionales</a>
  <ul class="collapse">
  <li><a href="#imputación-de-ceros" id="toc-imputación-de-ceros" class="nav-link" data-scroll-target="#imputación-de-ceros">2.1 - Imputación de ceros</a></li>
  <li><a href="#transformación-clr" id="toc-transformación-clr" class="nav-link" data-scroll-target="#transformación-clr">2.2 - Transformación CLR</a></li>
  </ul></li>
  <li><a href="#matriz-de-correlaciones" id="toc-matriz-de-correlaciones" class="nav-link" data-scroll-target="#matriz-de-correlaciones">3 - Matriz de correlaciones</a></li>
  <li><a href="#tendencias-temporales" id="toc-tendencias-temporales" class="nav-link" data-scroll-target="#tendencias-temporales">4 - Tendencias temporales</a></li>
  <li><a href="#análisis-en-componentes-principales" id="toc-análisis-en-componentes-principales" class="nav-link" data-scroll-target="#análisis-en-componentes-principales">5 - Análisis en componentes principales</a>
  <ul class="collapse">
  <li><a href="#acp-medianas-temporales" id="toc-acp-medianas-temporales" class="nav-link" data-scroll-target="#acp-medianas-temporales">ACP medianas temporales</a></li>
  </ul></li>
  <li><a href="#análisis-en-coordenadas-principales" id="toc-análisis-en-coordenadas-principales" class="nav-link" data-scroll-target="#análisis-en-coordenadas-principales">6 - Análisis en coordenadas principales</a></li>
  <li><a href="#ajuste-de-modelos-nbmm-y-nbzimm" id="toc-ajuste-de-modelos-nbmm-y-nbzimm" class="nav-link" data-scroll-target="#ajuste-de-modelos-nbmm-y-nbzimm">7 - Ajuste de modelos NBMM y NBZIMM</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Análisis exploratorio</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Juanjo Doblas </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introducción" class="level2">
<h2 class="anchored" data-anchor-id="introducción">1 - Introducción</h2>
<p>En este documento realizaremos un análisis exploratorio de los datos que se encuentran en el archivo <code>causas_muerte.xls</code>.</p>
<p>Esta tabla de datos contiene información sobre las causas de muerte en la mayoría de países del mundo desde el año 1990 hasta el 2019, así como algunas covariables.</p>
<p>Primero de todo cargaremos las librerías necesarias para realizar el análisis.</p>
<p>Ahora, carguemos nuestra base de datos y presentemos un resumen.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 6,000
Columns: 44
$ pais                     &lt;chr&gt; "Afganistán", "Afganistán", "Afganistán", "Af…
$ codigo_Pais              &lt;chr&gt; "AFG", "AFG", "AFG", "AFG", "AFG", "AFG", "AF…
$ año                      &lt;ord&gt; 1990, 1991, 1992, 1993, 1994, 1995, 1996, 199…
$ poblacion                &lt;dbl&gt; 10694796, 10745167, 12057433, 14003760, 15455…
$ meningitis               &lt;dbl&gt; 2159, 2218, 2475, 2812, 3027, 3102, 3193, 330…
$ alzheimer                &lt;dbl&gt; 1116, 1136, 1162, 1187, 1211, 1225, 1239, 125…
$ parkinson                &lt;dbl&gt; 371, 374, 378, 384, 391, 394, 398, 402, 405, …
$ def_nutricionales        &lt;dbl&gt; 2087, 2153, 2441, 2837, 3081, 3131, 3175, 325…
$ malaria                  &lt;dbl&gt; 93, 189, 239, 108, 211, 175, 175, 240, 563, 4…
$ ahogo                    &lt;dbl&gt; 1370, 1391, 1514, 1687, 1809, 1881, 1969, 207…
$ violencia_inter          &lt;dbl&gt; 1538, 2001, 2299, 2589, 2849, 2969, 3331, 302…
$ trastornos_maternos      &lt;dbl&gt; 2655, 2885, 3315, 3671, 3863, 4035, 4203, 435…
$ VIH                      &lt;dbl&gt; 34, 41, 48, 56, 63, 71, 78, 84, 89, 93, 97, 1…
$ trastornos_cons_drogas   &lt;dbl&gt; 93, 102, 118, 132, 142, 151, 159, 168, 173, 1…
$ tuberculosis             &lt;dbl&gt; 4661, 4743, 4976, 5254, 5470, 5628, 5821, 594…
$ enf_cardiovasculares     &lt;dbl&gt; 44899, 45492, 46557, 47951, 49308, 50158, 511…
$ infecciones_respi        &lt;dbl&gt; 23741, 24504, 27404, 31116, 33390, 34030, 347…
$ trastornos_neonatales    &lt;dbl&gt; 15612, 17128, 20060, 22335, 23288, 23722, 241…
$ trastornos_Cons_alcohol  &lt;dbl&gt; 72, 75, 80, 85, 88, 91, 93, 96, 97, 98, 99, 1…
$ autolesiones             &lt;dbl&gt; 696, 751, 855, 943, 993, 1032, 1070, 1104, 11…
$ exp_fuer_naturaleza      &lt;dbl&gt; 0, 1347, 614, 225, 160, 381, 70, 175, 7123, 7…
$ enf_diarreicas           &lt;dbl&gt; 4235, 4927, 6123, 8174, 8215, 9566, 9682, 106…
$ exp_amb_temperatura      &lt;dbl&gt; 175, 113, 38, 41, 44, 46, 49, 50, 51, 51, 52,…
$ neoplasias               &lt;dbl&gt; 11580, 11796, 12218, 12634, 12914, 13106, 133…
$ conflicto_terrorismo     &lt;dbl&gt; 1490, 3370, 4344, 4096, 8959, 5525, 3255, 672…
$ diabetes_mellitus        &lt;dbl&gt; 2108, 2120, 2153, 2195, 2231, 2248, 2298, 234…
$ enfermedad_crónica       &lt;dbl&gt; 3709, 3724, 3776, 3862, 3932, 3974, 4041, 409…
$ envenenamientos          &lt;dbl&gt; 338, 351, 386, 425, 451, 467, 485, 504, 505, …
$ desnutrición_energetica  &lt;dbl&gt; 2054, 2119, 2404, 2797, 3038, 3087, 3130, 320…
$ lesiones_carretera       &lt;dbl&gt; 4154, 4472, 5106, 5681, 6001, 6211, 6446, 667…
$ enfermedades_cronicas    &lt;dbl&gt; 5945, 6050, 6223, 6445, 6664, 6823, 7000, 716…
$ cirrosis_crónicas        &lt;dbl&gt; 2673, 2728, 2830, 2943, 3027, 3076, 3133, 320…
$ enfermedades_digestivas  &lt;dbl&gt; 5005, 5120, 5335, 5568, 5739, 5843, 5966, 609…
$ fuego_calientes          &lt;dbl&gt; 323, 332, 360, 396, 420, 434, 450, 469, 472, …
$ hepatitis_aguda          &lt;dbl&gt; 2985, 3092, 3325, 3601, 3816, 3946, 4098, 425…
$ total_muertes            &lt;dbl&gt; 147971, 156844, 169156, 182230, 194795, 19652…
$ pib                      &lt;dbl&gt; 6055.475, 1577.317, 5020.360, 10943.549, 6721…
$ idh                      &lt;dbl&gt; 0.273, 0.279, 0.287, 0.297, 0.292, 0.310, 0.3…
$ esperanza_vida_m         &lt;dbl&gt; 48.40, 49.14, 50.32, 52.74, 53.54, 54.09, 54.…
$ esperanza_vida_h         &lt;dbl&gt; 43.71, 44.35, 45.07, 50.22, 49.53, 51.04, 51.…
$ esperanza_vida           &lt;dbl&gt; 45.97, 46.66, 47.60, 51.47, 51.50, 52.54, 53.…
$ emisiones_CO2            &lt;dbl&gt; 2.910, 2.779, 1.696, 1.627, 1.555, 1.380, 1.3…
$ emisiones_CO2_PIB        &lt;dbl&gt; 0.10, 0.10, 0.06, 0.08, 0.10, 0.06, 0.06, 0.0…
$ emisiones_CO2_per_capita &lt;dbl&gt; 0.24, 0.21, 0.12, 0.11, 0.10, 0.08, 0.08, 0.0…</code></pre>
</div>
</div>
<section id="descripción-de-las-variables" class="level3">
<h3 class="anchored" data-anchor-id="descripción-de-las-variables">1.1 - Descripción de las variables</h3>
<p>Realicemos una pequeña descripción de cada variable:</p>
<ul>
<li><em>pais</em>: país del que proceden los datos. Veamos cuántos países se recogen.</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 200 × 1
   pais             
   &lt;chr&gt;            
 1 Afganistán       
 2 Albania          
 3 Argelia          
 4 Samoa Americana  
 5 Andorra          
 6 Angola           
 7 Antigua y Barbuda
 8 Argentina        
 9 Armenia          
10 Australia        
# ℹ 190 more rows</code></pre>
</div>
</div>
<ul>
<li><p><em>codigo_Pais</em>: código de 3 letras para los nombres de los países según la norma ISO 3166-1 alfa-3.</p></li>
<li><p><em>año</em>: año en el que se recogen los datos. Veamos que no falta ningún año en ningún país desde 1990 hasta 2019. Lo veremos en la siguiente tabla que recoge el número de muestras, y por tanto de países, por cada año.</p></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>año
1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 
 200  200  200  200  200  200  200  200  200  200  200  200  200  200  200  200 
2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 
 200  200  200  200  200  200  200  200  200  200  200  200  200  200 </code></pre>
</div>
</div>
<ul>
<li><em>población</em>: número de habitantes de cada país en cada año.</li>
</ul>
<p>Las variables desde la columna <em>meningitis</em> hasta <em>hepatitis_aguda</em> recogen el número de muertes por la causa que da nombre a la variable en cada país y cada año. Nos interesa saber cuantos conteos de ceros hay en cada variable. Lo vemos en la siguiente tabla:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1
Columns: 31
$ meningitis              &lt;int&gt; 196
$ alzheimer               &lt;int&gt; 60
$ parkinson               &lt;int&gt; 60
$ def_nutricionales       &lt;int&gt; 193
$ malaria                 &lt;int&gt; 3311
$ ahogo                   &lt;int&gt; 60
$ violencia_inter         &lt;int&gt; 105
$ trastornos_maternos     &lt;int&gt; 335
$ VIH                     &lt;int&gt; 178
$ trastornos_cons_drogas  &lt;int&gt; 460
$ tuberculosis            &lt;int&gt; 136
$ enf_cardiovasculares    &lt;int&gt; 0
$ infecciones_respi       &lt;int&gt; 6
$ trastornos_neonatales   &lt;int&gt; 62
$ trastornos_Cons_alcohol &lt;int&gt; 189
$ autolesiones            &lt;int&gt; 30
$ exp_fuer_naturaleza     &lt;int&gt; 3301
$ enf_diarreicas          &lt;int&gt; 99
$ exp_amb_temperatura     &lt;int&gt; 721
$ neoplasias              &lt;int&gt; 0
$ conflicto_terrorismo    &lt;int&gt; 3091
$ diabetes_mellitus       &lt;int&gt; 0
$ enfermedad_crónica      &lt;int&gt; 24
$ envenenamientos         &lt;int&gt; 484
$ desnutrición_energetica &lt;int&gt; 323
$ lesiones_carretera      &lt;int&gt; 30
$ enfermedades_cronicas   &lt;int&gt; 0
$ cirrosis_crónicas       &lt;int&gt; 30
$ enfermedades_digestivas &lt;int&gt; 17
$ fuego_calientes         &lt;int&gt; 256
$ hepatitis_aguda         &lt;int&gt; 720</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.783333</code></pre>
</div>
</div>
<p>Observamos que en las causas de muerte hay aproximadamente un 7,78% de ceros. Sin embargo, en algunas variables este porcentaje supera el 50%, por lo que estamos ante un modelo con exceso de ceros o <em>ZI</em> (por sus siglas en inglés <em>Zero-inflated model</em>). Esta característica la tendremos que tener en cuenta en el análisis.</p>
<ul>
<li><p><em>total_muertes</em>: Es el número de muertes totales que ha habido en cada año en cada país. Es la suma de todas las causas de muerte.</p></li>
<li><p><em>pib</em>: producto interior bruto en millones de dólares. Expresa el valor monetario de la producción de bienes y servicios de demanda final.</p></li>
<li><p><em>idh</em>: índice de desarrollo humano. Se calcula en base a la esperanza de vida, el nivel de educación y el ingreso per cápita.</p></li>
<li><p><em>esperanza_vida_m</em>: esperanza de vida de las mujeres en años.</p></li>
<li><p><em>esperanza_vida_h</em>: esperanza de vida de los hombres en años.</p></li>
<li><p><em>esperanza_vida</em>: esperanza de vida de la población en años.</p></li>
<li><p><em>emisiones_CO2</em>: cantidad de CO2 emitido en millones de toneladas.</p></li>
<li><p><em>emisiones_CO2_PIB</em>: cantidad de CO2 emitido por cada 1000 dólares de PIB en kilogramos.</p></li>
<li><p><em>emisiones_CO2_per_capita</em>: cantidad de CO2 emitido per cápita en toneladas.</p></li>
</ul>
</section>
</section>
<section id="tratamiento-de-datos-composicionales" class="level2">
<h2 class="anchored" data-anchor-id="tratamiento-de-datos-composicionales">2 - Tratamiento de datos composicionales</h2>
<p>Las variables que nos dan información sobre las causas de muerte tienen naturaleza composicional. En efecto, todas las entradas son positivas, ya que son conteos de muertes; y la única información relevante en cada fila es la contenida en su vector de proporciones, ya que este nos da el porcentaje de muertes por cada causa.</p>
<p>Antes de poder aplicar técnicas de análisis de datos composicionales hay que tratar los datos siguiendo los pasos siguientes:</p>
<ol type="1">
<li><p>Se sustituyen (<em>imputan</em>) los ceros.</p></li>
<li><p>Se transforman logarítmicamente los datos.</p></li>
</ol>
<section id="imputación-de-ceros" class="level3">
<h3 class="anchored" data-anchor-id="imputación-de-ceros">2.1 - Imputación de ceros</h3>
<p>Hay varias estrategias para imputar ceros. Nosotros sustituiremos los ceros por 0,65 ya que el porcentaje de ceros es menor al 10%.</p>
</section>
<section id="transformación-clr" class="level3">
<h3 class="anchored" data-anchor-id="transformación-clr">2.2 - Transformación CLR</h3>
<p>Utilizaremos la transformación logarítmica centrada, que consiste en dividir cada entrada por la media geométrica de la fila y aplicarle un logaritmo.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 6,000
Columns: 31
$ meningitis              &lt;dbl&gt; 0.60370104, 0.30271028, 0.38079966, 0.48855860…
$ alzheimer               &lt;dbl&gt; -0.05619325, -0.36638229, -0.37529808, -0.3739…
$ parkinson               &lt;dbl&gt; -1.157497, -1.477395, -1.498302, -1.502450, -1…
$ def_nutricionales       &lt;dbl&gt; 0.56978352, 0.27296661, 0.36696706, 0.49740978…
$ malaria                 &lt;dbl&gt; -2.54109990, -2.15990388, -1.95673246, -2.7709…
$ ahogo                   &lt;dbl&gt; 0.14886663, -0.16387270, -0.11068558, -0.02238…
$ violencia_inter         &lt;dbl&gt; 0.2645388, 0.1997514, 0.3070335, 0.4059343, 0.…
$ trastornos_maternos     &lt;dbl&gt; 0.8105005, 0.5656293, 0.6730169, 0.7551267, 0.…
$ VIH                     &lt;dbl&gt; -3.547339, -3.688079, -3.561995, -3.427741, -3…
$ trastornos_cons_drogas  &lt;dbl&gt; -2.541100, -2.776678, -2.662511, -2.570291, -2…
$ tuberculosis            &lt;dbl&gt; 1.3732859, 1.0627742, 1.0791856, 1.1136523, 1.…
$ enf_cardiovasculares    &lt;dbl&gt; 3.638471, 3.323641, 3.315237, 3.324842, 3.2715…
$ infecciones_respi       &lt;dbl&gt; 3.001259, 2.704941, 2.785248, 2.892385, 2.8817…
$ trastornos_neonatales   &lt;dbl&gt; 2.582096, 2.346819, 2.473287, 2.560818, 2.5214…
$ trastornos_Cons_alcohol &lt;dbl&gt; -2.797033, -3.084163, -3.051169, -3.010441, -3…
$ autolesiones            &lt;dbl&gt; -0.5283497, -0.7802452, -0.6820945, -0.6040264…
$ exp_fuer_naturaleza     &lt;dbl&gt; -7.5044823, -0.1960157, -1.0132011, -2.0369923…
$ enf_diarreicas          &lt;dbl&gt; 1.2774392, 1.1008347, 1.2866114, 1.5556210, 1.…
$ exp_amb_temperatura     &lt;dbl&gt; -1.908913, -2.674263, -3.795610, -3.739521, -3…
$ neoplasias              &lt;dbl&gt; 2.283335, 1.973865, 1.977470, 1.991054, 1.9317…
$ conflicto_terrorismo    &lt;dbl&gt; 0.23283201, 0.72101713, 0.94335485, 0.86467351…
$ diabetes_mellitus       &lt;dbl&gt; 0.57979552, 0.25752048, 0.24142148, 0.24084467…
$ enfermedad_crónica      &lt;dbl&gt; 1.1448182, 0.8209027, 0.8032245, 0.8058478, 0.…
$ envenenamientos         &lt;dbl&gt; -1.250653, -1.540865, -1.477359, -1.401003, -1…
$ desnutrición_energetica &lt;dbl&gt; 0.55384500, 0.25704867, 0.35169328, 0.48321004…
$ lesiones_carretera      &lt;dbl&gt; 1.258128, 1.003940, 1.104976, 1.191790, 1.1653…
$ enfermedades_cronicas   &lt;dbl&gt; 1.616606, 1.306163, 1.302811, 1.317967, 1.2701…
$ cirrosis_crónicas       &lt;dbl&gt; 0.8172573, 0.5096731, 0.5148360, 0.5340921, 0.…
$ enfermedades_digestivas &lt;dbl&gt; 1.4444933, 1.1392588, 1.1488482, 1.1716985, 1.…
$ fuego_calientes         &lt;dbl&gt; -1.296047, -1.596516, -1.547092, -1.471678, -1…
$ hepatitis_aguda         &lt;dbl&gt; 0.92765564, 0.63492252, 0.67602894, 0.73587421…</code></pre>
</div>
</div>
</section>
</section>
<section id="matriz-de-correlaciones" class="level2">
<h2 class="anchored" data-anchor-id="matriz-de-correlaciones">3 - Matriz de correlaciones</h2>
<p>Analicemos la matriz de correlaciones de las causas de muerte y las covariables. Usaremos la correlación de Spearman y no la de Pearson ya que nuestras variables de interés, las causas de muerte, son discretas.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analisis_exploratorio_files/figure-html/matriz%20correlacion-1.png" class="img-fluid figure-img" width="2880"></p>
</figure>
</div>
</div>
</div>
<p>Fijémonos primero en las correlaciones entre causas de muerte y covariables. La variable <em>población</em> apenas tiene correlación con las causas de muerte. En <em>pib</em>, <em>emisiones_CO2</em> y <em>emisiones_CO2_PIB</em> tampoco vemos muchas correlaciones altas. Estas se ven sobre todo en <em>emisiones_CO2_per_capita</em> y en las variables que explican la esperanza de vida, incluido el IDH ya que la esperanza de vida es un factor importante a la hora de calcular el índice y se puede ver en la alta correlación entre el IDH y la esperanza de vida. Estas variables están altamente correlacionadas con muchas causas de muerte, tanto positivamente como negativamente. Veamos a qué se podría deber esto. Normalmente, la poca esperanza de vida y las pocas emisiones de CO2 per cápita se suelen asociar a países pocos desarrollados y podemos ver en las correlaciones negativas las enfermedades que suelen ser comunes en estos países: meningitis, deficiencias nutricionales, malaria, enfermedades diarreicas, etc. Luego, en las correlaciones positivas, podemos ver enfermedades asociadas con la vejez: alzheimer, parkinson y enfermedades cardiovasculares; así como trastornos como consecuencia de drogas o alcohol, autolesiones, neoplasias (cánceres), enfermedades crónicas, etc.</p>
<p>Por último, vemos que hay algunas enfermedades bastante correlacionadas y otras que no. La correlación positiva que más destaca es entre deficiencias nutricionales y desnutrición energética (causas muy parecidas), con un valor de <span class="math inline">\(0.98\)</span>; mientras que la correlación negativa más destacada es entre neoplasias y trastornos maternos, con un valos de <span class="math inline">\(-0.89\)</span>. Las dos correlaciones más pequeñas con un valor de <span class="math inline">\(0.00\)</span> corresponden a infecciones respiratorias con malaria; e infecciones respiratorias con neoplasias.</p>
<p>Cabe destacar el caso de la variable <em>total_muertes</em> que no tiene ninguna correlación considerable exceptuando con <em>población</em> (obviamente), <em>emisiones_CO2</em> y <em>pib</em>, aunque estas dos últimas también están altamente correlacionadas con <em>población</em>.</p>
</section>
<section id="tendencias-temporales" class="level2">
<h2 class="anchored" data-anchor-id="tendencias-temporales">4 - Tendencias temporales</h2>
<p>En este apartado vamos a estudiar de manera global las tendencias temporales de cada enfermedad.</p>
<p>Vamos a trabajar con un tibble donde sumaremos todas las causas por cada año, con lo que nos quedarán <span class="math inline">\(30\)</span> filas, una para cada año, y los conteos serán mundiales.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 30
Columns: 32
$ año                     &lt;ord&gt; 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997…
$ meningitis              &lt;dbl&gt; 432253, 428621, 426440, 420836, 413799, 409826…
$ alzheimer               &lt;dbl&gt; 560607, 583156, 605884, 629560, 652164, 674803…
$ parkinson               &lt;dbl&gt; 147153, 150872, 154883, 160246, 164378, 168879…
$ def_nutricionales       &lt;dbl&gt; 756807, 729144, 700663, 674218, 649800, 723094…
$ malaria                 &lt;dbl&gt; 840297, 858984, 856415, 862216, 855671, 862626…
$ ahogo                   &lt;dbl&gt; 460454, 454369, 447050, 445428, 443344, 437297…
$ violencia_inter         &lt;dbl&gt; 372491, 383683, 407170, 432852, 441965, 444240…
$ trastornos_maternos     &lt;dbl&gt; 302418, 298270, 299299, 293563, 293147, 290549…
$ VIH                     &lt;dbl&gt; 336059, 430725, 540070, 664463, 800169, 938439…
$ trastornos_cons_drogas  &lt;dbl&gt; 56133, 61890, 66826, 71603, 76717, 79985, 8170…
$ tuberculosis            &lt;dbl&gt; 1776724, 1786386, 1807737, 1774708, 1753808, 1…
$ enf_cardiovasculares    &lt;dbl&gt; 12062027, 12220127, 12437821, 12801949, 130261…
$ infecciones_respi       &lt;dbl&gt; 3318235, 3282912, 3258763, 3226943, 3187256, 3…
$ trastornos_neonatales   &lt;dbl&gt; 3004571, 2975078, 2950367, 2924477, 2896497, 2…
$ trastornos_Cons_alcohol &lt;dbl&gt; 116389, 122476, 131663, 143900, 153858, 156713…
$ autolesiones            &lt;dbl&gt; 738791, 752562, 770273, 791890, 817668, 825908…
$ exp_fuer_naturaleza     &lt;dbl&gt; 50216, 156552, 12030, 21369, 12717, 19169, 148…
$ enf_diarreicas          &lt;dbl&gt; 2894954, 2903082, 2871806, 2798612, 2740296, 2…
$ exp_amb_temperatura     &lt;dbl&gt; 55072, 56658, 59926, 66812, 72305, 72635, 6760…
$ neoplasias              &lt;dbl&gt; 5752482, 5867847, 5995978, 6166947, 6295941, 6…
$ conflicto_terrorismo    &lt;dbl&gt; 116286, 85017, 62063, 62733, 566082, 67210, 87…
$ diabetes_mellitus       &lt;dbl&gt; 661066, 679609, 702232, 728055, 751232, 773466…
$ enfermedad_crónica      &lt;dbl&gt; 600911, 613574, 630144, 647239, 665349, 683683…
$ envenenamientos         &lt;dbl&gt; 87950, 87812, 88434, 90035, 90897, 90352, 8886…
$ desnutrición_energetica &lt;dbl&gt; 655974, 631012, 606014, 583918, 564045, 641083…
$ lesiones_carretera      &lt;dbl&gt; 1112753, 1117007, 1125549, 1137428, 1153626, 1…
$ enfermedades_cronicas   &lt;dbl&gt; 3092730, 3148257, 3207785, 3266581, 3297260, 3…
$ cirrosis_crónicas       &lt;dbl&gt; 1012405, 1026851, 1042934, 1067711, 1089312, 1…
$ enfermedades_digestivas &lt;dbl&gt; 1854367, 1877489, 1903733, 1939530, 1967643, 1…
$ fuego_calientes         &lt;dbl&gt; 123122, 123939, 124993, 127492, 129610, 128522…
$ hepatitis_aguda         &lt;dbl&gt; 166343, 165276, 163687, 161899, 159423, 157173…</code></pre>
</div>
</div>
<p>Ahora lo transformamos en una serie temporal y elaboramos los gráficos.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analisis_exploratorio_files/figure-html/graficos%201-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>En estos primeros diez gráficos podemos observar un claro descenso constante del número de muertes por meningitis, deficiencias nutricionales, ahogo y transtornos maternos. A partir del 2010 también hay un descenso de las muertes por malaria. Por otro lado, hay un aumento constante de las muertes por alzheimer, parkinson y trantornos por consecuencia de drogas. Luego, el VIH alcanzó el máximo de muertes en 2004 y desde entonces han ido bajando. De forma similar, las muertes por violencia interpersonal alcanzaron el máximo en 2002 y después bajaron hasta mantenerse alrededor de 420000 muertes, un número superior a las 380000 muertes en 1990.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analisis_exploratorio_files/figure-html/graficos%202-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Aquí podemos apreciar el descenso de muertes en tuberculosis, infecciones respiratorias, trastornos neonatales y enfermedades diarreicas. En cuanto ascenso de muertes podemos ver las causas enfermedades cardiovasculares, trastornos como consecuencia del alcohol y neoplasias. Por otro lado, las autolesiones y exposiciones al ambiente y temperatura tuvieron una subida con posterior bajada de tal forma que en 2019 hay los mismos conteos que en 1990 aproximadamente. Cabe destacar el caso de la exposición a las fuerzas de la naturaleza, con un nivel aproximadamente constante por debajo de 50000 exceptuando algunos años que rozan las 250000 muertes.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analisis_exploratorio_files/figure-html/graficos%203-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analisis_exploratorio_files/figure-html/graficos%204-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>En estos últimos once gráficos podemos ver un ascenso en diabetes mellitus, enfermedades crónicas, cirrosis crónicas, enfermedades digestivas y lesiones carretera, aunque esta última ha bajado con respecto a los últimos diez años. También vemos un descenso en envenenamientos, desnutriciones energéticas, exposición al fuego y sustancias calientes y hepatitis aguda. Las causas por conflictos terroristas han mantenido un nivel relativamente constante alrededor de 10000 muertes con un pico en 50000 en el año 1994.</p>
</section>
<section id="análisis-en-componentes-principales" class="level2">
<h2 class="anchored" data-anchor-id="análisis-en-componentes-principales">5 - Análisis en componentes principales</h2>
<p>En este apartado realizaremos un análisis en componentes principales (ACP). Nos restringiremos a los datos que proporcionan los países europeos. Primero vamos a filtrar los países de este continente en nuestra base de datos.</p>
<p>Antes de realizar el ACP veamos cómo se distribuyen las muertes totales por año.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analisis_exploratorio_files/figure-html/distribucion%20muertes%20por%20año-1.png" class="img-fluid figure-img" width="1440"></p>
</figure>
</div>
</div>
</div>
<p>Como podemos ver, hay algunas causas de defunción que apenas causan impacto. Por ello, con el objetivo de reducir dimensionalidad, vamos a agruparlas siguiendo el criterio de la OMS en <a href="https://icd.who.int/browse/2024-01/mms/en">este enlace</a>. Los grupos que nos quedan son los siguientes:</p>
<ul>
<li><p>Enfermedades infecciosas o parasitarias (<em>enf_infec_paras</em>). En este grupo incluimos <em>meningitis</em>, <em>malaria</em>, <em>VIH</em> y <em>tuberculosis</em>.</p></li>
<li><p>Enfermedades del sistema nervioso (<em>enf_sist_nervioso</em>). En este grupo incluimos <em>alzheimer</em> y <em>parkinson</em>.</p></li>
<li><p>Enfermedades endocrinas, nutricionales o metabólicas (<em>enf_metabolicas</em>). En este grupo incluimos <em>def_nutricionales</em>, <em>diabetes_mellitus</em> y <em>desnutrición_energetica</em>.</p></li>
<li><p>Causas externas de morbilidad o mortalidad, lesiones y envenenamientos (<em>causas_externas</em>). En este grupo incluimos <em>ahogo</em>, <em>violencia_inter</em>, <em>autolesiones</em>, <em>exp_fuer_naturaleza</em>, <em>conflicto_terrorismo</em>, <em>lesiones_carretera</em>, <em>exp_amb_temperatura</em>, <em>envenenamientos</em> y <em>fuego_calientes</em>.</p></li>
<li><p>Causas relacionadas con el embarazo, parto o puerperio (en la madre) y afecciones en el periodo perinatal (en el hijo) (<em>trastornos_embarazo</em>). En este grupo incluimos <em>trastornos_maternos</em> y <em>trastornos_neonatales</em>.</p></li>
<li><p>Trastornos mentales, del comportamiento o del desarrollo neurológico (<em>trastornos_mentales</em>). En este grupo incluimos <em>trastornos_cons_drogas</em> y <em>trastornos_Cons_alcohol</em>.</p></li>
<li><p>Enfermedades del sistema circulatorio (<em>enf_cardiovasculares</em>). En este grupo incluimos <em>enf_cardiovasculares</em>.</p></li>
<li><p>Enfermedades del sistema respiratorio (<em>infecciones_respi</em>). En este grupo incluimos <em>infecciones_respi</em>.</p></li>
<li><p>Enfermedades del sistema digestivo (<em>enf_sist_digestivo</em>). En este grupo incluimos <em>enf_diarreicas</em>, <em>cirrosis_crónicas</em>, <em>enfermedades_digestivas</em> y <em>hepatitis_aguda</em>.</p></li>
<li><p>Neoplasias (<em>neoplasias</em>). En este grupo incluimos <em>neoplasias</em>.</p></li>
<li><p>Enfermedades crónicas (<em>enf_cronicas</em>). En este grupo incluimos <em>enfermedad_crónica</em> y <em>enfermedades_cronicas</em>.</p></li>
</ul>
<p>Creemos la nueva base de datos con las causas de muerte agrupadas.</p>
<p>Veamos de nuevo cómo se distribuyen las muertes totales por año, ahora con la nueva agrupación.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analisis_exploratorio_files/figure-html/distribucion%20muertes%20agrupadas%20por%20año-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="acp-medianas-temporales" class="level3">
<h3 class="anchored" data-anchor-id="acp-medianas-temporales">ACP medianas temporales</h3>
<p>Haremos un primer análisis con un conjunto de datos donde para cada país tendremos la mediana de cada causa de muerte con respecto al tiempo. Construyamos primero este conjunto de datos.</p>
<p>Ahora, le aplicaremos la transformación <em>clr</em> y centraremos los datos. Notemos que no va a hacer falta imputar ceros ya que en ningún grupo de causas la mediana es 0.</p>
<p>Antes de realizar el método de componentes principales, observemos la matriz de varianzas-covarianzas y la matriz de correlación.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Matriz de varianzas-covarianzas</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                     enf_infec_paras enf_sist_nervioso enf_metabolicas
enf_infec_paras           0.46176283       -0.21668982     -0.19003765
enf_sist_nervioso        -0.21668982        0.20206636      0.08241400
enf_metabolicas          -0.19003765        0.08241400      0.43169162
causas_externas           0.13816649       -0.08446363     -0.12376265
trastornos_embarazo       0.12416973       -0.19540815      0.01111443
trastornos_mentales       0.05360760       -0.03189322     -0.39076469
enf_cardiovasculares      0.03453357       -0.04152905     -0.02231976
infecciones_respi        -0.14908708        0.09354538      0.01554908
enf_sist_digestivo        0.02774952       -0.02013273     -0.01011550
neoplasias               -0.16143373        0.12269747      0.06711215
enf_cronicas             -0.12274148        0.08939340      0.12911895
                     causas_externas trastornos_embarazo trastornos_mentales
enf_infec_paras           0.13816649         0.124169734         0.053607603
enf_sist_nervioso        -0.08446363        -0.195408152        -0.031893223
enf_metabolicas          -0.12376265         0.011114430        -0.390764688
causas_externas           0.17545407        -0.074611067         0.126634950
trastornos_embarazo      -0.07461107         0.734491809        -0.291589646
trastornos_mentales       0.12663495        -0.291589646         0.757467691
enf_cardiovasculares      0.06947524         0.006936123        -0.004122759
infecciones_respi        -0.11745958        -0.033259840        -0.061533780
enf_sist_digestivo        0.03009011        -0.082060035        -0.002268012
neoplasias               -0.04919710        -0.146720744        -0.004262477
enf_cronicas             -0.09032683        -0.053062610        -0.151275659
                     enf_cardiovasculares infecciones_respi enf_sist_digestivo
enf_infec_paras               0.034533574       -0.14908708        0.027749518
enf_sist_nervioso            -0.041529054        0.09354538       -0.020132729
enf_metabolicas              -0.022319759        0.01554908       -0.010115496
causas_externas               0.069475239       -0.11745958        0.030090105
trastornos_embarazo           0.006936123       -0.03325984       -0.082060035
trastornos_mentales          -0.004122759       -0.06153378       -0.002268012
enf_cardiovasculares          0.103377099       -0.09464323        0.016391988
infecciones_respi            -0.094643231        0.25367918       -0.021638036
enf_sist_digestivo            0.016391988       -0.02163804        0.088622682
neoplasias                   -0.012500719        0.03087068       -0.012132301
enf_cronicas                 -0.055598501        0.08397722       -0.014507684
                       neoplasias enf_cronicas
enf_infec_paras      -0.161433732  -0.12274148
enf_sist_nervioso     0.122697473   0.08939340
enf_metabolicas       0.067112150   0.12911895
causas_externas      -0.049197098  -0.09032683
trastornos_embarazo  -0.146720744  -0.05306261
trastornos_mentales  -0.004262477  -0.15127566
enf_cardiovasculares -0.012500719  -0.05559850
infecciones_respi     0.030870684   0.08397722
enf_sist_digestivo   -0.012132301  -0.01450768
neoplasias            0.108818335   0.05674843
enf_cronicas          0.056748428   0.12827475</code></pre>
</div>
</div>
<p>Podemos ver que los valores de las varianzas se agrupan entre <span class="math inline">\(0.088622682\)</span> y <span class="math inline">\(0.757467691\)</span>, siendo el valor mínimo de <em>enf_sist_digestivo</em> y el máximo de <em>trastornos_mentales</em>. Veamos de una forma más clara las varianzas ordenadas de menor a mayor.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  enf_sist_digestivo enf_cardiovasculares           neoplasias 
          0.08862268           0.10337710           0.10881834 
        enf_cronicas      causas_externas    enf_sist_nervioso 
          0.12827475           0.17545407           0.20206636 
   infecciones_respi      enf_metabolicas      enf_infec_paras 
          0.25367918           0.43169162           0.46176283 
 trastornos_embarazo  trastornos_mentales 
          0.73449181           0.75746769 </code></pre>
</div>
</div>
<p>Por otro lado, la matriz de correlaciones es:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analisis_exploratorio_files/figure-html/matriz%20correlacion%20medianas-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En cuanto a las correlaciones, la mayor correlación positiva se encuentra entre <em>enf_sist_nervioso</em> y <em>neoplasias</em>, con un valor de <span class="math inline">\(0.74\)</span>. Por otro lado, la mayor correlación negativa se encuentra entre <em>enf_infec_para</em> y <em>neoplasias</em> y entre <em>enf_metabolicas</em> y <em>trastornos_mentales</em>, ambas con un valor de <span class="math inline">\(-0.66\)</span>.</p>
<p>Pasemos al estudio de las componentes principales. Haremos dos ACP: uno con los datos escalados y otro sin escalar. Calculamos los valores y vectores propios de la matriz de varianzas-covarianzas.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Vectores propios (datos sin escalar)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                             PC1         PC2         PC3         PC4
enf_infec_paras       0.26609872  0.45556719 -0.36644347 -0.50473537
enf_sist_nervioso    -0.12162398 -0.35557878  0.08428323 -0.01279787
enf_metabolicas      -0.47781071 -0.12750375 -0.32453041  0.28095224
causas_externas       0.23667660  0.09498203 -0.30473429  0.11127339
trastornos_embarazo  -0.27278135  0.68332298  0.51862395  0.26114511
trastornos_mentales   0.69433474 -0.20571336  0.36179996  0.26768292
enf_cardiovasculares  0.05435860  0.07718967 -0.20995873  0.31963201
infecciones_respi    -0.14355040 -0.18605194  0.41607633 -0.58383118
enf_sist_digestivo    0.04278399 -0.02126764 -0.20694930 -0.10055961
neoplasias           -0.07068484 -0.25426553  0.01233269  0.15385983
enf_cronicas         -0.20780137 -0.16068087  0.01950005 -0.19262147
                             PC5         PC6          PC7         PC8
enf_infec_paras       0.28503943  0.33086671  0.019351441  0.22107466
enf_sist_nervioso    -0.20261652  0.50351171  0.083139258  0.18076732
enf_metabolicas       0.58096697 -0.24869200 -0.189231233  0.17828461
causas_externas      -0.33994194 -0.15286414 -0.541524402 -0.42805555
trastornos_embarazo  -0.02061494  0.04939466  0.073853878 -0.08388819
trastornos_mentales   0.40590594 -0.09199034  0.008921872  0.01505170
enf_cardiovasculares -0.43481661 -0.06091465 -0.048391486  0.42195042
infecciones_respi    -0.13172467 -0.38671048 -0.306854964  0.25573778
enf_sist_digestivo   -0.15813628 -0.47990891  0.737505735 -0.12566555
neoplasias           -0.11009920  0.34917756  0.128432886  0.02526844
enf_cronicas          0.12603781  0.18812987  0.034797017 -0.66052565
                              PC9        PC10       PC11
enf_infec_paras       0.005701503 -0.04124383 -0.3015113
enf_sist_nervioso    -0.435778111  0.48633916 -0.3015113
enf_metabolicas      -0.111493718  0.02968901 -0.3015113
causas_externas      -0.348224588 -0.04626222 -0.3015113
trastornos_embarazo  -0.122985142  0.01007989 -0.3015113
trastornos_mentales   0.046927911  0.07992872 -0.3015113
enf_cardiovasculares  0.587759361  0.18790817 -0.3015113
infecciones_respi     0.037807916 -0.10955781 -0.3015113
enf_sist_digestivo   -0.196337789  0.01712204 -0.3015113
neoplasias            0.013728167 -0.81501527 -0.3015113
enf_cronicas          0.522894491  0.20101214 -0.3015113</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Vectores propios (datos escalados)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                            PC1         PC2         PC3          PC4
enf_infec_paras       0.3787142  0.15744764 -0.09321594 -0.223181079
enf_sist_nervioso    -0.3942161 -0.29192038  0.03418269  0.113445548
enf_metabolicas      -0.2795177  0.26490138  0.46706691 -0.033756595
causas_externas       0.3648751 -0.25828722  0.16596405 -0.003798498
trastornos_embarazo   0.1139598  0.58617466 -0.10511176  0.279460633
trastornos_mentales   0.1739732 -0.47855669 -0.40301920  0.145803122
enf_cardiovasculares  0.2471098 -0.10524547  0.50985551  0.316720160
infecciones_respi    -0.2984498  0.06218235 -0.43541218 -0.254765992
enf_sist_digestivo    0.1082963 -0.17982702  0.29383074 -0.760128534
neoplasias           -0.3521964 -0.34520973  0.17708733  0.239709650
enf_cronicas         -0.4009312  0.11848920  0.06116345 -0.190620319
                               PC5        PC6         PC7         PC8
enf_infec_paras      -4.820244e-01  0.1547622  0.44315765  0.37394143
enf_sist_nervioso    -8.245305e-05  0.1574309  0.32310165  0.27417077
enf_metabolicas      -2.217588e-01 -0.2555787 -0.52402415  0.33975689
causas_externas      -2.139113e-01  0.4557198 -0.36984218 -0.25190648
trastornos_embarazo   3.138475e-01 -0.1692791  0.18512330 -0.25892209
trastornos_mentales  -2.117727e-02 -0.4194585 -0.22491578 -0.12333245
enf_cardiovasculares  4.055886e-01  0.3242944  0.09320174  0.01199238
infecciones_respi     3.963548e-01  0.4920011 -0.25123050  0.22380033
enf_sist_digestivo    3.742916e-01 -0.2700176  0.16209067 -0.10785958
neoplasias           -2.932137e-02 -0.1042977  0.30697536 -0.02112712
enf_cronicas         -3.334899e-01  0.2065015  0.10326537 -0.67937073
                             PC9         PC10       PC11
enf_infec_paras       0.17193928 -0.131121414 -0.3660752
enf_sist_nervioso    -0.31196331  0.620503806 -0.2421630
enf_metabolicas       0.05082045  0.002453506 -0.3539547
causas_externas      -0.51457140 -0.056686590 -0.2256538
trastornos_embarazo  -0.33527401  0.015121534 -0.4616941
trastornos_mentales   0.28436544  0.118948552 -0.4688597
enf_cardiovasculares  0.50400538  0.071227023 -0.1732100
infecciones_respi     0.10550915 -0.235482486 -0.2713334
enf_sist_digestivo   -0.12228962  0.014729830 -0.1603738
neoplasias           -0.15530476 -0.711230570 -0.1777100
enf_cronicas          0.32901223  0.116594217 -0.1929441</code></pre>
</div>
</div>
<p>En el caso de los datos sin escalar, la primera componente principal le da peso mayoritariamente a la variable <em>trastornos_mentales</em> y <em>enf_metabolicas</em> y apenas le da peso a <em>enf_cardiovasculares</em>, <em>enf_sist_digestivo</em> y <em>neoplasias</em>. Considerando la segunda componente, vemos que seguimos sin darle peso a <em>enf_cardiovasculares</em> y <em>enf_sist_digestivo</em>. Esto se debe a que son las variables con menos varianza.</p>
<p>Por otro lado, en el caso de datos escalados, podemos ver que entre la primera y segunda componente le dan un peso considerable a todas las variables.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Valores propios (datos sin escalar)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>         eigenvalue variance.percent cumulative.variance.percent
Dim.1  1.268195e+00     3.680508e+01                    36.80508
Dim.2  1.073763e+00     3.116234e+01                    67.96742
Dim.3  4.462382e-01     1.295056e+01                    80.91798
Dim.4  2.524932e-01     7.327762e+00                    88.24574
Dim.5  1.399434e-01     4.061385e+00                    92.30713
Dim.6  1.021272e-01     2.963897e+00                    95.27102
Dim.7  6.446778e-02     1.870960e+00                    97.14198
Dim.8  4.628405e-02     1.343238e+00                    98.48522
Dim.9  3.447640e-02     1.000561e+00                    99.48578
Dim.10 1.771839e-02     5.142163e-01                   100.00000
Dim.11 4.912935e-30     1.425814e-28                   100.00000</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Valores propios (datos escalados)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>         eigenvalue variance.percent cumulative.variance.percent
Dim.1  4.315340e+00     3.923036e+01                    39.23036
Dim.2  2.086199e+00     1.896544e+01                    58.19580
Dim.3  1.528367e+00     1.389424e+01                    72.09005
Dim.4  1.066680e+00     9.697091e+00                    81.78714
Dim.5  6.105770e-01     5.550700e+00                    87.33784
Dim.6  4.512528e-01     4.102299e+00                    91.44014
Dim.7  3.380435e-01     3.073122e+00                    94.51326
Dim.8  2.503674e-01     2.276067e+00                    96.78933
Dim.9  2.266238e-01     2.060216e+00                    98.84954
Dim.10 1.265503e-01     1.150457e+00                   100.00000
Dim.11 1.584937e-29     1.440852e-28                   100.00000</code></pre>
</div>
</div>
<p>A partir de esta tabla de valores podemos ver que con dos componentes principales nos permiten explicar aproximadamente el <span class="math inline">\(68\%\)</span> de la variación total con los datos sin escalar; y el <span class="math inline">\(58\%\)</span> con los datos escalados. Para ver de una manera más detallada el peso de estas componentes, podemos hacer el siguiente gráfico, donde se muestra un diagrama de barras donde a cada dimensión le asociamos el porcentaje de variación que explica:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analisis_exploratorio_files/figure-html/porcentajes%20variacion%20medianas-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<p>En ambos casos, a partir de la tabla y el gráfico podemos elegir dos o tres componentes principales, ya que a partir de la cuarta componente el porcentaje de variabilidad no aumenta lo suficiente como para considerar una dimensión más. Representemos estas variables en el espacio.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analisis_exploratorio_files/figure-html/circulo%20correlacion%20dim1-dim2%20medianas-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>En el primer gráfico vemos que las variables mejor representadas son <em>trastornos_embarazo</em> y <em>trastornos_mentales</em> ya que tienen la flecha más larga. También se puede apreciar que son las que más contribuyen al plano principal. Esto es debido a que son las variables con mayor varianza. Por otro lado, <em>enf_cardiovasculares</em> y <em>enf_sist_nervioso</em> son las peores representadas y las que menos contribuyen, debido a que tienen la menor varianza.</p>
<p>En el segundo gráfico, la mayoría de variables están bien representadas y contribuyen aproximadamente lo mismo al plano principal, exceptuando de nuevo <em>enf_cardiovasculares</em> y <em>enf_sist_nervioso</em>, aunque en este caso la diferencia no es tan grande.</p>
<p>Podemos ver las contribuciones de cada variable al plano principal</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analisis_exploratorio_files/figure-html/contribuciones%20plano%20principal%20medianas-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Veamos también la calidad de representación de las variables:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analisis_exploratorio_files/figure-html/grafico%20barras%20cos2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Por último veamos una representación de los países en el plano principal con un biplot.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analisis_exploratorio_files/figure-html/biplots%20dim1-dim2-1.png" class="img-fluid figure-img" width="1920"></p>
</figure>
</div>
</div>
</div>
<p>Podemos ver que la agrupación de países no difiere mucho de un gráfico a otro.</p>
</section>
</section>
<section id="análisis-en-coordenadas-principales" class="level2">
<h2 class="anchored" data-anchor-id="análisis-en-coordenadas-principales">6 - Análisis en coordenadas principales</h2>
<p>Realicemos también un análisis en coordenadas principales (o escalamiento multidimensional). Este análisis se hará sobre las causas de muerte. Por su naturaleza composicional, no podemos utilizar las distancias Euclídea o de Manhattan. En su lugar, utilizaremos la distancia de Aitchison, que es la distancia Euclídea entre dos muestras después de aplicar la transformación CLR. Mostremos las distancias entre los primeros 8 elementos de la tabla.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>         1        2         3         4         5         6        7         8
1 0.000000 7.517644 6.9380412 5.9133714 5.6964994 6.3675080 4.744665 5.6514798
2 7.517644 0.000000 1.4772406 2.3819334 2.7682095 2.0475318 3.456650 2.7353589
3 6.938041 1.477241 0.0000000 1.3934617 1.6490610 0.9432203 2.476086 1.6279306
4 5.913371 2.381933 1.3934617 0.0000000 1.0314078 0.6500082 1.403295 0.9228985
5 5.696499 2.768210 1.6490610 1.0314078 0.0000000 1.0190817 1.388755 0.4950372
6 6.367508 2.047532 0.9432203 0.6500082 1.0190817 0.0000000 1.772533 0.8995822
7 4.744665 3.456650 2.4760859 1.4032946 1.3887549 1.7725334 0.000000 1.1292067
8 5.651480 2.735359 1.6279306 0.9228985 0.4950372 0.8995822 1.129207 0.0000000</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>NULL</code></pre>
</div>
</div>
<p>Ahora, aplicamos el método de coordenadas principales con la función de R <code>cmdscale</code>, usando la matriz de distancias anterior y especificando <span class="math inline">\(k = 2\)</span> (dos componentes principales).</p>
<p>Por último, calculemos los coeficientes de precisión a partir de los valores propios de la matriz de productos cruzados.</p>
<ul>
<li><span class="math inline">\(m_{1,2} =\)</span> <code>#m_12</code></li>
<li><span class="math inline">\(m_{2,2} =\)</span> <code>#m_22</code></li>
</ul>
</section>
<section id="ajuste-de-modelos-nbmm-y-nbzimm" class="level2">
<h2 class="anchored" data-anchor-id="ajuste-de-modelos-nbmm-y-nbzimm">7 - Ajuste de modelos NBMM y NBZIMM</h2>
<p>Vamos a ajustar los modelos NBMM y NBZIMM a los datos de países europeos. Un primer ajuste será intentar explicar una causa de muerte a partir de una covariable. Veamos los conteos de ceros que hay para los datos europeos.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1
Columns: 31
$ meningitis              &lt;int&gt; 60
$ alzheimer               &lt;int&gt; 0
$ parkinson               &lt;int&gt; 0
$ def_nutricionales       &lt;int&gt; 60
$ malaria                 &lt;int&gt; 1323
$ ahogo                   &lt;int&gt; 30
$ violencia_inter         &lt;int&gt; 45
$ trastornos_maternos     &lt;int&gt; 144
$ VIH                     &lt;int&gt; 2
$ trastornos_cons_drogas  &lt;int&gt; 60
$ tuberculosis            &lt;int&gt; 30
$ enf_cardiovasculares    &lt;int&gt; 0
$ infecciones_respi       &lt;int&gt; 0
$ trastornos_neonatales   &lt;int&gt; 26
$ trastornos_Cons_alcohol &lt;int&gt; 30
$ autolesiones            &lt;int&gt; 0
$ exp_fuer_naturaleza     &lt;int&gt; 721
$ enf_diarreicas          &lt;int&gt; 44
$ exp_amb_temperatura     &lt;int&gt; 60
$ neoplasias              &lt;int&gt; 0
$ conflicto_terrorismo    &lt;int&gt; 783
$ diabetes_mellitus       &lt;int&gt; 0
$ enfermedad_crónica      &lt;int&gt; 0
$ envenenamientos         &lt;int&gt; 55
$ desnutrición_energetica &lt;int&gt; 99
$ lesiones_carretera      &lt;int&gt; 0
$ enfermedades_cronicas   &lt;int&gt; 0
$ cirrosis_crónicas       &lt;int&gt; 0
$ enfermedades_digestivas &lt;int&gt; 0
$ fuego_calientes         &lt;int&gt; 60
$ hepatitis_aguda         &lt;int&gt; 168</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.882655</code></pre>
</div>
</div>
<p>Vemos que el porcentaje total de ceros ha subido un punto porcentual respecto a los datos totales y también cabe resaltar el caso de malaria, con casi la totalidad de ceros.</p>
<p>Vamos a elegir explicar algunas variables a partir del idh, ya que esta covariable está altamente relacionada con el resto de covariables. Escogeremos meningitis, con un bajo conteo de ceros y alta correlación negativa con idh; hepatitis aguda, con un conteo medio de ceros y alta correlación negativa con idh; y malaria, con un alto conteo de ceros y alta correlación negativa con idh.</p>
<p>Primero, realicemos los ajustes con el modelo NBMM.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'nlme'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    collapse</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'MASS'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    select</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Computational iterations: 6 
Computational time: 0.002 minutes </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed-effects model fit by maximum likelihood
  Data: data_eu 
  AIC BIC logLik
   NA  NA     NA

Random effects:
 Formula: ~1 | pais
        (Intercept) Residual
StdDev:   0.6161808 1.014256

Variance function:
 Structure: fixed weights
 Formula: ~invwt 
Fixed effects:  meningitis ~ idh + offset(log(N)) 
                Value Std.Error   DF   t-value p-value
(Intercept) -3.766330 0.1537664 1333 -24.49384       0
idh         -4.495228 0.1573183 1333 -28.57409       0
 Correlation: 
    (Intr)
idh -0.8  

Standardized Within-Group Residuals:
       Min         Q1        Med         Q3        Max 
-2.9554564 -0.4911119 -0.1279091  0.3203499 11.4409886 

Number of Observations: 1380
Number of Groups: 46 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Computational iterations: 14 
Computational time: 0.003 minutes </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed-effects model fit by maximum likelihood
  Data: data_eu 
  AIC BIC logLik
   NA  NA     NA

Random effects:
 Formula: ~1 | pais
        (Intercept)  Residual
StdDev:    1.138522 0.8422958

Variance function:
 Structure: fixed weights
 Formula: ~invwt 
Fixed effects:  hepatitis_aguda ~ idh + offset(log(N)) 
                Value Std.Error   DF   t-value p-value
(Intercept) -6.668336 0.2489094 1333 -26.79021       0
idh         -3.557043 0.2308526 1333 -15.40829       0
 Correlation: 
    (Intr)
idh -0.722

Standardized Within-Group Residuals:
       Min         Q1        Med         Q3        Max 
-2.5064600 -0.4232228 -0.1351154  0.2313729 11.4647231 

Number of Observations: 1380
Number of Groups: 46 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Computational iterations: 17 
Computational time: 0.004 minutes </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed-effects model fit by maximum likelihood
  Data: data_eu 
  AIC BIC logLik
   NA  NA     NA

Random effects:
 Formula: ~1 | pais
        (Intercept)  Residual
StdDev:    3.979688 0.2092159

Variance function:
 Structure: fixed weights
 Formula: ~invwt 
Fixed effects:  malaria ~ idh + offset(log(N)) 
                 Value Std.Error   DF   t-value p-value
(Intercept) -16.900290 0.9309877 1333 -18.15308       0
idh          -4.063456 0.3064729 1333 -13.25878       0
 Correlation: 
    (Intr)
idh -0.249

Standardized Within-Group Residuals:
        Min          Q1         Med          Q3         Max 
-4.62022605 -0.05123046 -0.03674516 -0.02557496  8.69191442 

Number of Observations: 1380
Number of Groups: 46 </code></pre>
</div>
</div>
<p>Ahora ajustaremos el modelo ZINBMM.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Computational iterations: 6 
Computational time: 0.001 minutes </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed-effects model fit by maximum likelihood
  Data: data_eu 
  AIC BIC logLik
   NA  NA     NA

Random effects:
 Formula: ~1 | pais
        (Intercept) Residual
StdDev:   0.6161807 1.014256

Variance function:
 Structure: fixed weights
 Formula: ~invwt 
Fixed effects:  meningitis ~ idh + offset(log(N)) 
                Value Std.Error   DF   t-value p-value
(Intercept) -3.766330 0.1537664 1333 -24.49385       0
idh         -4.495228 0.1573183 1333 -28.57409       0
 Correlation: 
    (Intr)
idh -0.8  

Standardized Within-Group Residuals:
       Min         Q1        Med         Q3        Max 
-2.9554579 -0.4911119 -0.1279092  0.3203499 11.4409860 

Number of Observations: 1380
Number of Groups: 46 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Computational iterations: 14 
Computational time: 0.004 minutes </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed-effects model fit by maximum likelihood
  Data: data_eu 
  AIC BIC logLik
   NA  NA     NA

Random effects:
 Formula: ~1 | pais
        (Intercept)  Residual
StdDev:    1.138522 0.8422958

Variance function:
 Structure: fixed weights
 Formula: ~invwt 
Fixed effects:  hepatitis_aguda ~ idh + offset(log(N)) 
                Value Std.Error   DF   t-value p-value
(Intercept) -6.668336 0.2489094 1333 -26.79021       0
idh         -3.557043 0.2308526 1333 -15.40829       0
 Correlation: 
    (Intr)
idh -0.722

Standardized Within-Group Residuals:
       Min         Q1        Med         Q3        Max 
-2.5064597 -0.4232228 -0.1351154  0.2313729 11.4647236 

Number of Observations: 1380
Number of Groups: 46 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Computational iterations: 17 
Computational time: 0.004 minutes </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed-effects model fit by maximum likelihood
  Data: data_eu 
  AIC BIC logLik
   NA  NA     NA

Random effects:
 Formula: ~1 | pais
        (Intercept)  Residual
StdDev:    4.079143 0.1771226

Variance function:
 Structure: fixed weights
 Formula: ~invwt 
Fixed effects:  malaria ~ idh + offset(log(N)) 
                 Value Std.Error   DF   t-value p-value
(Intercept) -17.290770 0.9226450 1333 -18.74044       0
idh          -3.369597 0.1481706 1333 -22.74133       0
 Correlation: 
    (Intr)
idh -0.121

Standardized Within-Group Residuals:
        Min          Q1         Med          Q3         Max 
-5.71301050 -0.05163879 -0.03740628 -0.02657194  8.39822015 

Number of Observations: 1380
Number of Groups: 46 </code></pre>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>